# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-10 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=90)),
                ('geography', models.CharField(max_length=90)),
                ('productName', models.CharField(max_length=90)),
                ('file_name', models.TextField()),
                ('uploaded_file', models.TextField()),
                ('system_model', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=90)),
                ('last_name', models.CharField(max_length=90)),
                ('username', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='actdata',
            name='user_uploaded',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets_uploaded', to='ecoinvent_app.User'),
        ),
    ]
